# .github/workflows/image-generation.yml
name: Daily Image Generation

on:
  schedule:
    # Run daily at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  generate-images:
    runs-on: ubuntu-latest
    timeout-minutes: 360 # 6 hours max
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        pip install google-genai pillow
        
    - name: Create output directory
      run: mkdir -p output
      
    - name: Generate images with all API keys
      env:
        GEN_KEYS: ${{ secrets.GEN_KEYS }}
      run: python image_generator.py
      
    - name: Upload generated images
      uses: actions/upload-artifact@v3
      with:
        name: generated-images-${{ github.run_number }}
        path: output/
        retention-days: 30
        
    - name: Commit and push results (optional)
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add output/ || true
        git add logs/ || true
        git commit -m "Daily image generation - $(date)" || exit 0
        git push || true
